name: Activity Box

on:
  schedule:
    - cron: '* */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: iamar7/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: iamar7
          GIST_ID: 8bf3dae8bf4e4811cf564bdfcbc91f73
